-- Jalankan di Supabase SQL Editor setelah project dibuat.
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id text not null,
  language text not null,
  elapsed_seconds integer not null check (elapsed_seconds > 0),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

create policy "Users can insert their own scores"
on public.scores for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can read leaderboard scores"
on public.scores for select
to authenticated
using (true);