create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(username) between 3 and 20),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "Profiles readable by authenticated" on public.profiles;
create policy "Profiles readable by authenticated"
on public.profiles for select to authenticated using (true);

-- Profil dibuat otomatis saat user daftar (username dari metadata signUp)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  base_name text;
  final_name text;
begin
  base_name := regexp_replace(
    coalesce(nullif(new.raw_user_meta_data->>'username', ''), split_part(new.email, '@', 1)),
    '[^a-zA-Z0-9_]', '', 'g'
  );
  if char_length(base_name) < 3 then
    base_name := 'player' || substr(replace(new.id::text, '-', ''), 1, 6);
  end if;
  base_name := left(base_name, 16);
  final_name := base_name;

  -- kalau bentrok, tambah suffix acak
  while exists (select 1 from public.profiles where lower(username) = lower(final_name)) loop
    final_name := base_name || floor(random() * 900 + 100)::int::text;
  end loop;

  insert into public.profiles (id, username) values (new.id, final_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ---------- SCORES (latihan solo + kemenangan duel) ----------
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  problem_id text not null,
  language text not null,
  elapsed_seconds integer not null check (elapsed_seconds > 0),
  source text not null default 'practice',
  created_at timestamptz not null default now()
);
alter table public.scores add column if not exists source text not null default 'practice';
create index if not exists scores_problem_time_idx on public.scores (problem_id, elapsed_seconds);
create index if not exists scores_user_problem_idx on public.scores (user_id, problem_id);

alter table public.scores enable row level security;

drop policy if exists "Users can insert their own scores" on public.scores;
create policy "Users can insert their own scores"
on public.scores for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read leaderboard scores" on public.scores;
create policy "Users can read leaderboard scores"
on public.scores for select to authenticated using (true);

-- Peringkat: waktu terbaik per pemain per soal
create or replace function public.get_leaderboard(p_problem text, p_days int default null)
returns table (rank bigint, user_id uuid, username text, language text, best_seconds int)
language sql
stable
as $$
  with best as (
    select distinct on (s.user_id) s.user_id, s.language, s.elapsed_seconds
    from public.scores s
    where s.problem_id = p_problem
      and (p_days is null or s.created_at >= now() - make_interval(days => p_days))
    order by s.user_id, s.elapsed_seconds asc, s.created_at asc
  )
  select row_number() over (order by b.elapsed_seconds, p.username) as rank,
         b.user_id, p.username, b.language, b.elapsed_seconds
  from best b
  join public.profiles p on p.id = b.user_id
  order by 1
  limit 50;
$$;

-- Rata-rata waktu & jumlah pemain per soal
create or replace function public.get_problem_stats(p_problem text)
returns table (avg_seconds numeric, players bigint)
language sql
stable
as $$
  select round(avg(t.best)), count(*)
  from (
    select min(s.elapsed_seconds) as best
    from public.scores s
    where s.problem_id = p_problem
    group by s.user_id
  ) t;
$$;

-- Waktu server (untuk sinkronisasi timer duel)
create or replace function public.server_now()
returns timestamptz
language sql stable
as $$ select now(); $$;

-- ---------- DUEL 1v1 ----------
create table if not exists public.duels (
  id uuid primary key default gen_random_uuid(),
  problem_id text not null,
  player1 uuid not null references public.profiles(id) on delete cascade,
  player2 uuid references public.profiles(id) on delete cascade,
  status text not null default 'waiting'
    check (status in ('waiting', 'active', 'finished', 'cancelled')),
  started_at timestamptz,
  finished_at timestamptz,
  winner uuid references public.profiles(id),
  winner_seconds integer,
  created_at timestamptz not null default now()
);
create index if not exists duels_waiting_idx on public.duels (status, created_at);

create table if not exists public.duel_events (
  id bigint generated by default as identity primary key,
  duel_id uuid not null references public.duels(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  passed integer not null,
  total integer not null,
  created_at timestamptz not null default now()
);
create index if not exists duel_events_duel_idx on public.duel_events (duel_id, id);

alter table public.duels enable row level security;
alter table public.duel_events enable row level security;

-- Client hanya boleh MEMBACA duel miliknya. Semua penulisan lewat RPC di bawah.
drop policy if exists "Players read own duels" on public.duels;
create policy "Players read own duels"
on public.duels for select to authenticated
using (auth.uid() = player1 or auth.uid() = player2);

drop policy if exists "Players read own duel events" on public.duel_events;
create policy "Players read own duel events"
on public.duel_events for select to authenticated
using (exists (
  select 1 from public.duels d
  where d.id = duel_id and (auth.uid() = d.player1 or auth.uid() = d.player2)
));

-- Cari lawan: gabung ke duel yang menunggu, atau buat baru
create or replace function public.find_duel(p_problem text)
returns public.duels
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  d public.duels;
begin
  if me is null then raise exception 'Belum login'; end if;

  -- bersihkan duel menunggu yang basi (> 2 menit)
  update public.duels set status = 'cancelled'
  where status = 'waiting' and created_at < now() - interval '2 minutes';

  -- duel aktif yang terbengkalai (> 15 menit) dibatalkan
  update public.duels set status = 'cancelled'
  where status = 'active' and started_at < now() - interval '15 minutes';

  -- kalau saya sudah punya duel aktif/menunggu, lanjutkan itu
  select * into d from public.duels
  where (player1 = me or player2 = me) and status in ('waiting', 'active')
  order by created_at desc limit 1;
  if found then return d; end if;

  -- gabung ke duel orang lain
  select * into d from public.duels
  where status = 'waiting' and player1 <> me
  order by created_at asc
  limit 1
  for update skip locked;

  if found then
    update public.duels
    set player2 = me, status = 'active', started_at = now()
    where id = d.id
    returning * into d;
    return d;
  end if;

  insert into public.duels (problem_id, player1) values (p_problem, me)
  returning * into d;
  return d;
end;
$$;

create or replace function public.cancel_duel(p_duel uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.duels set status = 'cancelled'
  where id = p_duel and player1 = auth.uid() and status = 'waiting';
end;
$$;

-- Lapor progres test (dipakai buat feed & progress bar lawan)
create or replace function public.duel_progress(p_duel uuid, p_passed int, p_total int)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare me uuid := auth.uid();
begin
  if not exists (
    select 1 from public.duels
    where id = p_duel and status = 'active' and (player1 = me or player2 = me)
  ) then
    return;
  end if;
  insert into public.duel_events (duel_id, user_id, passed, total)
  values (p_duel, me, greatest(p_passed, 0), greatest(p_total, 1));
end;
$$;

-- Selesai: yang pertama memanggil ini menang. Waktu dihitung di SERVER.
create or replace function public.duel_finish(p_duel uuid, p_language text)
returns public.duels
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  d public.duels;
  secs int;
begin
  select * into d from public.duels
  where id = p_duel and (player1 = me or player2 = me)
  for update;

  if not found then raise exception 'Duel tidak ditemukan'; end if;
  if d.status <> 'active' then return d; end if;

  secs := greatest(1, floor(extract(epoch from (now() - d.started_at)))::int);

  update public.duels
  set status = 'finished', winner = me, winner_seconds = secs, finished_at = now()
  where id = d.id
  returning * into d;

  insert into public.scores (user_id, problem_id, language, elapsed_seconds, source)
  values (me, d.problem_id, coalesce(p_language, 'javascript'), secs, 'duel');

  return d;
end;
$$;

-- Menyerah: lawan otomatis menang (tanpa skor)
create or replace function public.duel_forfeit(p_duel uuid)
returns public.duels
language plpgsql
security definer
set search_path = public
as $$
declare
  me uuid := auth.uid();
  d public.duels;
begin
  select * into d from public.duels
  where id = p_duel and (player1 = me or player2 = me)
  for update;
  if not found then raise exception 'Duel tidak ditemukan'; end if;
  if d.status <> 'active' then return d; end if;

  update public.duels
  set status = 'finished',
      winner = case when player1 = me then player2 else player1 end,
      finished_at = now()
  where id = d.id
  returning * into d;
  return d;
end;
$$;

revoke all on function public.find_duel(text) from public, anon;
revoke all on function public.cancel_duel(uuid) from public, anon;
revoke all on function public.duel_progress(uuid, int, int) from public, anon;
revoke all on function public.duel_finish(uuid, text) from public, anon;
revoke all on function public.duel_forfeit(uuid) from public, anon;
grant execute on function public.duel_forfeit(uuid) to authenticated;
grant execute on function public.find_duel(text) to authenticated;
grant execute on function public.cancel_duel(uuid) to authenticated;
grant execute on function public.duel_progress(uuid, int, int) to authenticated;
grant execute on function public.duel_finish(uuid, text) to authenticated;

-- ---------- REALTIME ----------
do $$
begin
  begin alter publication supabase_realtime add table public.duels; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.duel_events; exception when duplicate_object then null; end;
end $$;
